name: kimit_tours
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  auto_size_text: ^3.0.0
  http: ^0.13.5

  font_awesome_flutter: ^10.2.1
  url_launcher: ^6.1.7
  hidable: ^1.0.3
  card_swiper: ^2.0.4
  material_color_generator: ^1.1.0
  scroll_app_bar: ^2.0.0
  chewie: ^1.3.5
  icon_broken: ^1.1.0
  floating_frosted_bottom_bar: ^0.0.1
  country_picker: ^2.0.16
  flutter_image_slideshow: ^0.1.4
  smooth_page_indicator: ^1.0.0+2
  shared_preferences: ^2.0.15
  animated_text_kit: ^4.2.2
  carousel_slider: ^4.1.1
  shrink_sidemenu: ^2.0.0+2-null-safety
  keframe: ^3.0.0
  flutter_bloc: ^8.1.1
  readmore: ^2.1.0
  accordion: ^2.5.1
  flutter_expand_view: ^1.6.2
  scroll_page_view: ^1.0.2
  fluttertoast: ^8.1.1
  intl: ^0.18.0
  intl_phone_field: ^3.1.0

  cloud_firestore: ^4.0.3
  fluttericon: ^2.0.0



  #FIREBASE LIBS
  firebase_core: ^2.1.1
  firebase_auth: ^4.1.0
  flutter_bounceable: ^1.0.3
  page_transition: ^2.0.9
  circular_profile_avatar: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    #categories_images
    - assets/images/categories/day_tour.jpg
    - assets/images/categories/full_packages.jpg
    - assets/images/categories/excursions.jpg
    - assets/images/login.jpg
    - assets/images/register.jpg
    - assets/images/verify.jpg
    - assets/images/categories/discover.jpg
    - assets/images/categories/nile_cruise.jpg
    - assets/images/first_onboarding.jpg
    - assets/images/chatbot.png
    - assets/images/giza_pyramid_location.jpg
    - assets/images/second_onboarding.jpg
    - assets/images/last_onboarding.jpg
    - assets/images/splashtwo.jpg
    - assets/images/banner1.jpg
    - assets/images/banner2.jpg
    - assets/images/banner3.jpg
    - assets/images/home_scaffold.jpg
    - assets/images/day_tour.png
    - assets/images/fb_sign.png
    - assets/images/contact_us_vector.jpg
    - assets/images/gmail_sign.png
    - assets/images/cruise.png
    - assets/images/discover.png
    - assets/images/excursions.png
    - assets/images/tour_package.png
    - assets/images/2banner.jpg
    - assets/images/3banner.jpg
    - assets/images/white_scaffold.jpg
    - assets/images/dark_scaffold.jpg
    - assets/images/kimit_logo.png
    - assets/images/login_background.jpg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: oxygen
      fonts:
        - asset: assets/fonts/Oxygen-Regular.ttf
    - family: blessed
      fonts:
        - asset: assets/fonts/blessedday.otf

    - family: masque
      fonts:
        - asset: assets/fonts/masque.ttf

    - family: bonus
      fonts:
        - asset: assets/fonts/bonus.ttf

    - family: mesiri
      fonts:
        - asset: assets/fonts/Mesiri.ttf
    - family: worksans
      fonts:
        - asset: assets/fonts/WorkSans-Regular.ttf
    - family: lato
      fonts:
        - asset: assets/fonts/Lato-Bold.ttf
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
